### ISSUE TITLE
The preprocessor doesn't work when rollup.config.ts is an array of configs

### ISSUE THREAD

**Issue by elenaperezrioja** [lmarqs/cypress-rollup-preprocessor#463]
It is possible to have an array of rollup configs in rollup.config.ts instead of just one, if we want to build multiple bundles. The preprocessor doesn't support this.

## Current behavior
When passing the config:
`on(
    "file:preprocessor",
    rollupPreprocessor({
      rollupOptions: rollupConfig,
    })
  );`

## Expected behavior
Since the config is valid, we should accept it and run Cypress as expected.

## Steps to replicate behavior (include URLs)

1. Have a rollup.config.ts with multiple items.
2. Add the preprocessor code:
`on(
    "file:preprocessor",
    rollupPreprocessor({
      rollupOptions: rollupConfig,
    })
  );`
3. Run cypress. We get an error:
`Error: Could not resolve './commands' from cypress/support/e2e.ts
    at error (/Users/elenaperezrioja/Repos/front/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/Users/elenaperezrioja/Repos/front/node_modules/rollup/dist/shared/rollup.js:22508:24)
    at /Users/elenaperezrioja/Repos/front/node_modules/rollup/dist/shared/rollup.js:22471:26`

**Comment by lmarqs** [comment]
Hello @elenaperezrioja, thanks for the feedback.

Indeed the `rollupOptions` is not mean to be any valid rollup config, and I agree that this option name can be misleading.
I changed the API on the `1.0.1` version in order to avoid this kind of confusion and also allowing more customisations. Check here: https://github.com/lmarqs/cypress-rollup-preprocessor#options


I dont think that it would be possible to pass to `rollup` an array of options because `Cypress` is not able to handle more then one file as output per each test execution. But in case you have more than one output for the same source I recommend that you execute the tests separately for each `rollup`'s config.

How does it sounds to you?

**Comment by lmarqs** [comment]
Closing this issue due lack off activity
